version: "1.0"
info:
  model: int-scaffold
packages:
- name: VikashOnPremServiceValidationProject
  gitServerName: vikashSharmaGitRepo
  gitUrl: https://github.com/vikashsharma387/VikashOnPremServiceValidationProject
  gitUsername: vikashsharma387
  gitBranch: main
