version: "1.0"
info:
  model: int-scaffold
packages:
- name: VikashOnPremServiceValidationProject
  gitServerName: vikashSharmaGitRepo
  gitUrl: https://github.com/vikashsharma387/VikashOnPremServiceValidationProject
  gitUsername: vikashsharma387
  gitBranch: main
- name: webOnPremServiceValidationRepo
  gitServerName: vikashSharmaGitRepo
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
services:
- serviceName: project.vikashonpremservicevalidation.integrations:OnPremServiceCheckCRT
  packages:
  - name: VikashOnPremServiceValidationProject
    version: "1.0"
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: ServiceValidationOnPrem.flow:ClearPiplineFS
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.string:concat
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:clearPipeline
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: project.vikashonpremservicevalidation.integrations:OnPremServiceCheckERT
  packages:
  - name: VikashOnPremServiceValidationProject
    version: "1.0"
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: ServiceValidationOnPrem.flow:debugLog
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:getLastError
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:getLastError
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:getLastErrorFailureCaught
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:getRetryCount
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:getRetryCount
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:getSession
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:getSession
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:getTransportInfo
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:getTransportInfo
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:tracePipeLine
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:tracePipeline
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:setResponseAndResponseHeaders
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:setResponseHeader
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:setResponseHeaders
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:setResponse
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:setResponse2AndResponseCode
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.io:stringToStream
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:setResponseCode
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:setResponse2
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:setCustomLoggedFieldsAndCustomContextID
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:setCustomContextID
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:setCustomLoggedFields
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:setAuditLogFields
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:setAuditLogFields
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:setActivityLog
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:setActivityLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:restorePipeline
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:restorePipeline
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:SavePipline
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:savePipeline
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:ParentServiceForThrowExceptionCheck
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: ServiceValidationOnPrem.flow:throwExceptionForRetryChild
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:throwExceptionForRetry
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:GetDetailsforCallingService
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: ServiceValidationOnPrem.flow:getCallingService
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:getCallingService
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:getRetryCountService
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
