version: "1.0"
info:
  model: int-scaffold
packages:
- name: VikashOnPremServiceValidationProject
  gitServerName: vikashSharmaGitRepo
  gitUrl: https://github.com/vikashsharma387/VikashOnPremServiceValidationProject
  gitUsername: vikashsharma387
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.softwareag.com
  wpmRegistry: softwareag
- name: ShipmentPackage
  gitServerName: vikashNewGit
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
- name: webOnPremServiceValidationRepo
  gitServerName: vikashSharmaGitRepo
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
services:
- serviceName: project.vikashonpremservicevalidation.integrations:OnPremServiceCheckCRT
  packages:
  - name: VikashOnPremServiceValidationProject
    version: "1.0"
  - name: webOnPremServiceValidationRepo
    version: "1.0"
  - name: ShipmentPackage
    version: "1.0"
- serviceName: ServiceValidationOnPrem.flow:ClearPiplineFS
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.string:concat
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:clearPipeline
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: project.vikashonpremservicevalidation.integrations:OnPremServiceCheckERT
  packages:
  - name: VikashOnPremServiceValidationProject
    version: "1.0"
  - name: webOnPremServiceValidationRepo
    version: "1.0"
  - name: ShipmentPackage
    version: "1.0"
- serviceName: ServiceValidationOnPrem.flow:debugLog
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:getLastError
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:getLastError
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:getLastErrorFailureCaught
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:getRetryCount
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:getRetryCount
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:getSession
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:getSession
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:getTransportInfo
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:getTransportInfo
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:tracePipeLine
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:tracePipeline
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:setResponseAndResponseHeaders
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:setResponseHeader
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:setResponseHeaders
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:setResponse
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:setResponse2AndResponseCode
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.io:stringToStream
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:setResponseCode
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:setResponse2
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:setCustomLoggedFieldsAndCustomContextID
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:setCustomContextID
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:setCustomLoggedFields
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:setAuditLogFields
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:setAuditLogFields
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:setActivityLog
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:setActivityLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:restorePipeline
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:restorePipeline
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:SavePipline
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:savePipeline
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:ParentServiceForThrowExceptionCheck
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: ServiceValidationOnPrem.flow:throwExceptionForRetryChild
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:throwExceptionForRetry
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:GetDetailsforCallingService
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: ServiceValidationOnPrem.flow:getCallingService
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:getCallingService
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:getRetryCountService
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: ServiceValidationOnPrem.flow:SavePiplineToFile
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:savePipelineToFile
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: ServiceValidationOnPrem.flow:restorePipelineToFile
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:restorePipelineFromFile
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: project.vikashonpremservicevalidation.integrations:ConcatFlow
  packages:
  - name: VikashOnPremServiceValidationProject
    version: "1.0"
  - name: webOnPremServiceValidationRepo
    version: "1.0"
  - name: ShipmentPackage
    version: "1.0"
- serviceName: project.vikashonpremservicevalidation.integrations:ShipmentDetails
  packages:
  - name: VikashOnPremServiceValidationProject
    version: "1.0"
  - name: ShipmentPackage
    version: "1.0"
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: ShipmentPackage.flowService:GetShipmentByID
  packages:
  - name: ShipmentPackage
    version: "1.0"
- serviceName: project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_OnPrem_Conn
  packages:
  - name: VikashOnPremServiceValidationProject
    version: "1.0"
  - name: ShipmentPackage
    version: "1.0"
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: project.vikashonpremservicevalidation.integrations:GetDatafromOnPremDB
  packages:
  - name: VikashOnPremServiceValidationProject
    version: "1.0"
  - name: ShipmentPackage
    version: "1.0"
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:GetEmployeeData
  packages:
  - name: VikashOnPremServiceValidationProject
    version: "1.0"
  - name: ShipmentPackage
    version: "1.0"
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: ShipmentPackage.flowService:GetShipmentOnStatus
  packages:
  - name: ShipmentPackage
    version: "1.0"
- serviceName: ShipmentPackage.flowService:GetAllPurchaseOrderDetails
  packages:
  - name: ShipmentPackage
    version: "1.0"
- serviceName: ShipmentPackage.AdapterServices:SelectAdapterService
  packages:
  - name: ShipmentPackage
    version: "1.0"
- serviceName: ServiceValidationOnPrem.flow:InvokeService
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.flow:invokeService
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
configurationVariables:
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.databaseName
  : DataStore
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.password
  : "{AES}rGTLI7FSrEEUEWloN9T4rg=="
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.keyStore
  : ""
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.dbType
  : MSSQL
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.portNumber
  : "1433"
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.networkProtocol
  : ""
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.trustStore
  : ""
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.serverName
  : host.docker.internal
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionManagerSettings.poolable
  : "false"
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionEnabled
  : "false"
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.user
  : sa
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.VikashOnPremServiceValidationProject.project.vikashonpremservicevalidation.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OnPrem_Conn.connectionManagerSettings.minimumPoolSize
  : "0"
