version: "1.0"
info:
  model: int-scaffold
packages:
- name: VikashOnPremServiceValidationProject
  gitServerName: vikashSharmaGitRepo
  gitUrl: https://github.com/vikashsharma387/VikashOnPremServiceValidationProject
  gitUsername: vikashsharma387
  gitBranch: main
- name: webOnPremServiceValidationRepo
  gitServerName: vikashSharmaGitRepo
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
services:
- serviceName: project.vikashonpremservicevalidation.integrations:OnPremServiceCheckCRT
  packages:
  - name: VikashOnPremServiceValidationProject
    version: "1.0"
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: ServiceValidationOnPrem.flow:ClearPiplineFS
  packages:
  - name: webOnPremServiceValidationRepo
    version: "1.0"
- serviceName: pub.string:concat
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:clearPipeline
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: project.vikashonpremservicevalidation.integrations:OnPremServiceCheckERT
  packages:
  - name: VikashOnPremServiceValidationProject
    version: "1.0"
  - name: webOnPremServiceValidationRepo
    version: "1.0"
